// Auto-generated code. Do not edit.
namespace myImages {

    helpers._registerFactory("image", function(name: string) {
        switch(helpers.stringTrim(name)) {
            case "image1":
            case "hero":return img`
. . . . . . f f f f . . . . . . 
. . . . f f f 2 2 f f f . . . . 
. . . f f f 2 2 2 2 f f f . . . 
. . f f f e e e e e e f f f . . 
. . f f e 2 2 2 2 2 2 e e f . . 
. . f e 2 f f f f f f 2 e f . . 
. . f f f f e e e e f f f f . . 
. f f e f b f 4 4 f b f e f f . 
. f e e 4 1 f d d f 1 4 e e f . 
. . f e e d d d d d d e e f . . 
. . . f e e 4 4 4 4 e e f . . . 
. . e 4 f 2 2 2 2 2 2 f 4 e . . 
. . 4 d f 2 2 2 2 2 2 f d 4 . . 
. . 4 4 f 4 4 5 5 4 4 f 4 4 . . 
. . . . . f f f f f f . . . . . 
. . . . . f f . . f f . . . . . 
`;
            case "image2":
            case "heart":return img`
....................
....................
....................
....................
....................
....................
.......22...22......
......2322.2222.....
......232222222.....
......222222222.....
.......22222b2......
........222b2.......
.........222........
..........2.........
....................
....................
....................
....................
....................
....................
`;
            case "image3":
            case "bat":return img`
. . f f f . . . . . . . . f f f 
. f f c c . . . . . . f c b b c 
f f c c . . . . . . f c b b c . 
f c f c . . . . . . f b c c c . 
f f f c c . c c . f c b b c c . 
f f c 3 c c 3 c c f b c b b c . 
f f b 3 b c 3 b c f b c c b c . 
. c b b b b b b c b b c c c . . 
. c 1 b b b 1 b b c c c c . . . 
c b b b b b b b b b c c . . . . 
c b c b b b c b b b b f . . . . 
f b 1 f f f 1 b b b b f c . . . 
f b b b b b b b b b b f c c . . 
. f b b b b b b b b c f . . . . 
. . f b b b b b b c f . . . . . 
. . . f f f f f f f . . . . . . 
`;
        }
        return null;
    })

    helpers._registerFactory("animation", function(name: string) {
        switch(helpers.stringTrim(name)) {
            case "ghostLeft":
            case "anim1":return [img`
........................
........................
........................
..........ffff..........
........ff1111ff........
.......fb111111bf.......
......fbd1111111f.......
......fdd1111111df......
......fddd111111df......
......fdddddd111df......
......fdddddd111df......
......fbddddddd1df......
......ffbbddbfd1df......
.......fcbbdcfddbf......
.......fffbddccffff.....
.......ffffcfbbb1bcf....
......ffffffffcd1b1f....
...ffffffffff..fdfdf....
.....ffffff.....f.f.....
........................
........................
........................
........................
........................
`, img`
........................
........................
........................
........................
.........fffff..........
.......ffb1111ff........
......fb1111111bf.......
......f111111111f.......
.....ffff1111111df......
....fb111c1dd111df......
....ffb1b1fdcf11bf......
.....ffbfbfb11111f......
......ffffcfdb1b1f......
.......fcccfcfbfbf......
........ffffffffff......
.........ffffff.........
.........ffffff.........
.....f..fffffff.........
.....fffffffff..........
......fffffff...........
........................
........................
........................
........................
`];
        }
        return null;
    })

    helpers._registerFactory("song", function(name: string) {
        switch(helpers.stringTrim(name)) {

        }
        return null;
    })

}
// Auto-generated code. Do not edit.
